joomlatools/joomlatools-pages

- code/site/components/com_pages/template/page.php
Add a process:filters page property which can contain an array of additional page filters
> Allow to define template filters per page

- code/site/components/com_pages/dispatcher/behavior/cacheable.php
- code/site/components/com_pages/template/filter/form.php
Implement changes in: https://github.com/joomlatools/joomlatools-framework/pull/242
> Refactor cacheable behavior

- code/site/components/com_pages/data/registry.php
- code/site/components/com_pages/model/pages.php
- code/site/components/com_pages/page/registry.php
- code/site/components/com_pages/template/default.php
> #46 Add sanity checks

- code/site/components/com_pages/data/registry.php
- code/site/components/com_pages/model/behavior/sortable.php
- code/site/components/com_pages/model/pages.php
- code/site/components/com_pages/page/registry.php
- code/site/components/com_pages/template/default.php
> #48 Check for timestamps before converting

- code/site/components/com_pages/template/filter/toc.php
- code/site/components/com_pages/template/helper/behavior.php
> #58: Require an ID for header elements

- code/site/components/com_pages/dispatcher/router/resolver/abstract.php
- code/site/components/com_pages/dispatcher/router/resolver/page.php
- code/site/components/com_pages/page/registry.php
- code/site/components/com_pages/view/html.php
- code/site/components/com_pages/view/json.php
- code/site/components/com_pages/view/xml.php
This PR allows for the following:
route('.')
route('/')
route('./')
route('/about')
route('./about')
page('.')->route
page('/')->route
page('./')->route
page('/about')->route
page('./about')->route
> Fix route('index')

- code/site/components/com_pages/dispatcher/router/abstract.php
- code/site/components/com_pages/page/registry.php
To test ensure that both mysite?format=json returns a 404 error.
> Fix issue with formats

- code/site/components/com_pages/page/registry.php
To test check that: http://joomlatools.test/developer/ui/examples/list is working
> Static pages are no longer working 

- code/site/components/com_pages/template/filter/toc.php
This PR improves the toc filter by allowing heading anchors to be added to the page even if no <ktml:toc> placeholder has been defined.
> Improve toc filter

- code/site/components/com_pages/dispatcher/router/resolver/page.php
- code/site/components/com_pages/model/entity/page.php
- code/site/components/com_pages/template/filter/meta.php
This PR adds a canonical page property and it sets both the http header and html link accordingly.
> Make canonical a page property

- code/site/components/com_pages/view/html.php
> #154: proposed fix

- code/site/components/com_pages/template/filter/meta.php
To test, metadata should be working again.
> Fix metadata

- code/administrator/components/com_pages/pages.xml
- code/administrator/components/com_pages/version.php
- code/site/components/com_pages/controller/behavior/breadcrumbable.php
- code/site/components/com_pages/dispatcher/http.php
- code/site/components/com_pages/event/subscriber/errorhandler.php
This PR requires changes in https://github.com/joomlatools/joomlatools-framework/pull/317
> Fix error handling

- code/site/components/com_pages/controller/context/interface.php
- code/site/components/com_pages/dispatcher/behavior/cacheable.php
- code/site/components/com_pages/dispatcher/http.php
- code/site/components/com_pages/event/subscriber/errorhandler.php
This PR fixes a problem with error pages not  working correctly.
> Error pages not working

- code/site/components/com_pages/dispatcher/router/route/page.php
This PR fixes an issue with pagination routing. If the limit is fixed it's not correctly being removed from the route.
> Issue with pagination routing with fixed limit

- code/site/components/com_pages/controller/processor/webhook.php
This PR improves the webhook form processor `ComPagesControllerProcessorWebhook` and makes it more easily extendible and configurable.
- Added `method`, `headers` and `format` config options
- Added `getPayload()` method to transparently format the data based on format config option, by default the data will be send as `application/x-www-form-urlencoded`
> Improve webhook processor

- code/site/components/com_pages/event/subscriber/dispatcher.php
This PR fixes a bug in the pages routing and ensures that POST requests are dispatched to the correct component.
> Joomla login no longer working

- code/site/components/com_pages/resources/config/bootstrapper.php
See: joomlatools/joomlatools-framework#377
> Use identifiers when registering config formats

- code/site/components/com_pages/event/subscriber/errorhandler.php
The platform no longer uses JError.
> Add exception for Joomlatools Platform

- code/site/components/com_pages/config.php
- code/site/components/com_pages/event/subscriber/bootstrapper.php
This PR closes #475 and renames KPATH_PAGES to PAGES_SITE_ROOT
> Rename KPATH_PAGES to PAGES_SITE_ROOT

- code/site/components/com_pages/dispatcher/behavior/cacheable.php
- code/site/components/com_pages/model/cache.php
This PR closed #481 and ensures that the cache model will not return a listing if caching is disabled
> Do not list cached pages if caching is not enabled

- code/site/components/com_pages/controller/behavior/breadcrumbable.php
- code/site/components/com_pages/event/subscriber/dispatcher.php
- code/site/components/com_pages/event/subscriber/pagedecorator.php
- mason.js
> Fix notices

- code/site/components/com_pages/config.php
- code/site/components/com_pages/resources/config/site.php
- code/site/components/com_pages/resources/server/apache.txt
> Improve static cache config

- code/site/components/com_pages/model/webservice.php
> Fix notice in webservice model

- code/site/components/com_pages/resources/mason/revalidator.js
This PR closed #492 and adds support for custom headers to the cache revalidator
> Cache revalidator custom header support 

- code/site/components/com_pages/model/behavior/filterable.php
> Notice in ComPagesModelBehaviorFilterable

- code/site/components/com_pages/template/helper/behavior.php
Reverts joomlatools/joomlatools-pages#650
> Revert "Make ComPagesTemplateHelperBehavior::isLoaded() smart"
