code/site/components/com_pages/model/entity/page.php, code/site/components/com_pages/template/locator.php, code/site/components/com_pages/view/page/html.php
If a layout is defined in the page frontmatter it's loaded from the /layouts folder. If no layout is defined the default layout that is part of the component is loaded. 
The layout is is a relative path and can include subfolders. Example
- layout: file
- layout: folder/file
The layout follows the same naming conventions as the page, and is auto-discovered. The specific template engine is loaded based on the filename suffix.
1. As part of this change page template files no longer require to have a format suffix eg '.html'. 
2. As part of this change the module filter is now also available, this means that you can make use of the` <ktml:module position="[position]">[content]</ktml:module> `syntax to insert modules on the fly. 
The module filter should also be documented as it's very …
=> Load layouts from /layouts

code/site/components/com_pages/resources/config/bootstrapper.php, code/site/components/com_pages/template/locator/page.php, code/site/components/com_pages/template/locator/theme.php
Allow to import templates from within the active theme. Use theme:// 
Example:
`import('theme/includes/file')`
Will include the following file `/root/templates/[active]/includes/file` where `[active]` is the active template in Joomla.
=> Add theme:// template locator

code/site/components/com_pages/controller/page.php, code/site/components/com_pages/data/registry.php, code/site/components/com_pages/dispatcher/behavior/cacheable.php, code/site/components/com_pages/dispatcher/http.php, code/site/components/com_pages/pages.php, code/site/components/com_pages/resources/config/bootstrapper.php, code/site/components/com_pages/view/html.php
Implement http caching support through cacheable dispatcher behavior.  
This PR requires: https://github.com/joomlatools/joomlatools-framework/pull/180 and https://github.com/joomlatools/joomlatools-framework/pull/183 
It's best to read up on https://github.com/joomlatools/joomlatools-framework/issues/36 to if you are not familiar with http caching
See: https://github.com/joomlatools/joomlatools-framework/pull/183
Implemented a server side caching mechanism through the build in Joomla caching adapters. 
The server side cache key is based on the url, user and format, by not using the contents of the page we can return the response from cache for subsequent requests for the same resource. The longer our max-age, the longer the resource will remain valid in our server cache. 
Using a passive …
=> HTTP caching

code/site/components/com_pages/template/filter/asset.php
Allows to use theme:// in pages and templates. Will be rewritten to the base url of the active template.
=> Add theme:// asset path

code/site/components/com_pages/controller/page.php, code/site/components/com_pages/dispatcher/behavior/cacheable.php, code/site/components/com_pages/dispatcher/http.php, code/site/components/com_pages/event/subscriber/decorator.php, code/site/components/com_pages/page/registry.php, code/site/components/com_pages/resources/config/bootstrapper.php, code/site/components/com_pages/router.php, code/site/components/com_pages/view/html.php
This PR implements the ability to decorate  an existing Joomla menu item or page. The Joomla rendering cycle is intercepted after the active component has been dispatched and the returned by the  component is then injected in a page to be decorated.
To decorate an existing menu item or page create a page with the same name as the menu item alias, or the page route.
Example: `http://mysite.com/path/to/menu` => `/joomlatools-pages/pages/path/to/menu`
In the page place a `<ktml:content>` which will acted as the placeholder for output generated by the component and then place mark around it. The decorated result will be injected back into Joomla after processing.
- Frontmatter defined in the page will overwrite the Joomla menu item settings. If no frontmatter is defined the menu settings will …
=> Page decoration

code/site/components/com_pages/template/abstract.php
PR adds a template attribute([name), [value]) method.
- If the value is empty no attribute will be generated
- If the value is an array the values will be seperated using a space
=> Add attribute() method

code/site/components/com_pages/dispatcher/router/route.php, code/site/components/com_pages/model/behavior/sortable.php, code/site/components/com_pages/page/registry.php
Pages can be ordered per folder by adding a .order.[format] file to the folder that specifies the specific ordering of all the data files, both files and directories can be ordered.`Type`can be any data format: YAML, JSON, INI, PHP, and XML.
Example with YAML:
```yaml
- file1.md
- fileB.md
- folderA
- folderB
```
=> Implement page ordering support

code/site/components/com_pages/data/object.php
fixes #51
On joomlatools site this would be used on partials/global/testimonial.html.php
$testimonials = data('testimonials')->flatten();
would be replaced by:
$testimonials = data('testimonials')->flatten(true);
so that we have access to the testimonial extension through $testimonial->folder. This would allow us to do this on the global extensions page: https://dsh.re/44f7a (see docman and logman labels below rating)
=> Allow keeping track of data folder when flattening 

code/site/components/com_pages/model/entity/page.php, code/site/components/com_pages/template/filter/plugins.php, code/site/components/com_pages/view/page/html.php
To pass the content to the content plugins for processing wrap it in a `<ktml:plugins>[...]</ktml:plugins>` block. Example:
```html
<ktml:plugins>
Content goes here
</ktml:plugins> 
```
The content is passed to the following plugin events :
- onContentBeforeDisplay
- onContentPrepare
- onConntentAfterDisplay
The result is returned and the `<ktml:plugins></ktml:plugins>` block replaced with the result.
Plugin processing is not enabled by default it needs to be enabled by adding the `plugins` filter to the `process:filters` list in the page frontmatter.
=> Content plugins page filter

code/site/components/com_pages/controller/abstract.php, code/site/components/com_pages/data/client.php, code/site/components/com_pages/data/registry.php, code/site/components/com_pages/model/collection.php, code/site/components/com_pages/model/factory.php, code/site/components/com_pages/model/page.php, code/site/components/com_pages/model/pages.php, code/site/components/com_pages/model/remote.php, code/site/components/com_pages/resources/config/bootstrapper.php, code/site/components/com_pages/view/html.php, code/site/components/com_pages/view/json.php, code/site/components/com_pages/view/xml.php
This PR implements support for remote for collections. A collection can now easily be retrieved from any URL. The implementation offers support for URI templates to make creating dynamic URL's easy.
A remote collection can be defined easily by specifying the url where the collection should be retrieved from. For example:
```yaml
collection:
source: remote?url=http://www.example.com
```
`remote`is a shortcut for `com:pages.model.remote`
The `url`parameter defines the location for the remote collection and can be templated using the [template URI's](https://tools.ietf.org/html/rfc6570) standard. When  a template uri is used the model state will be used to expand the template url.  For example:
```yaml
collection:
source: remote?url=http://example.com{+path}{/segments*}{?query,data*}
state: …
```
=> Remote collections

code/site/components/com_pages/dispatcher/behavior/cacheable.php, code/site/components/com_pages/resources/config/bootstrapper.php
This PR adds a new http_cache_time_proxy setting to allows defining the s-maxage cache directive. The default cache time is set to 15min and the shared proxy cache time is set to 2h.
See also: https://github.com/joomlatools/joomlatools-framework/pull/266
=> Add http_cache_time_proxy setting

code/site/components/com_pages/model/controller.php, code/site/components/com_pages/model/factory.php
This PR allows to use a model identifier as a collection source. Example:
```yaml
collection:
source: com:component.controller.item 
state: []
```
This PR requires: https://github.com/joomlatools/joomlatools-framework/pull/268
=> Controller collections

code/site/components/com_pages/data/registry.php, code/site/components/com_pages/model/filesystem.php, code/site/components/com_pages/template/default.php
This PR implements support for filesystem collections. A collection can now easily be retrieved from any path. The implementation offers support for URI templates to make creating dynamic path easy.
A filesystem collection can be defined easily by specifying the path where the collection should be retrieved from. For example:
```yaml
collection:
source: filesystem?path=data://team/members
```
`filesystem`is a shortcut for `com:pages.model.filesystem`
The `path`parameter defines the location for the filesystem collection and can be templated using the [template URI's](https://tools.ietf.org/html/rfc6570) standard. When  a template uri is used the model state will be used to expand the template url.  For example:
```yaml
collection:
source: filesystem?path=data://{+path}{/segments*}
state: …
```
=> Filesystem collections

code/site/components/com_pages/data/object.php, code/site/components/com_pages/template/default.php
This PR adds several improvements to the data objects. 
It's now possible to cast a data object to a string. You can do so by calling the `data([..])->toString()` method, or you can cast the the data object to a string `<?= data([...]) ?>`
It's now possible to create a new data object from an associative array of data. Example
```php
<? $data = data([
'foo' => 'bar',
'dog' => 'bark'
]) ?>
```
A none associative array is not supported. This will be interpreted as an array of data locations, see also https://github.com/joomlatools/joomlatools-pages/pull/4
=> Data JSON support

code/site/components/com_pages/controller/abstract.php, code/site/components/com_pages/model/entity/page.php, code/site/components/com_pages/resources/config/bootstrapper.php, code/site/components/com_pages/view/html.php
This PR implements automatic support for opengraph and additionally twitter cards. For an overview of both standards please see:
- http://ogp.me/#metadata
- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup
- og:type; defaults to `website`
- og:image; defaults to `page image`
- og:title; defaults to `page title`
- og:description; defaults to `page description`
- og:url, defaults to the `page url`
For opengraph metadata to be added to the page both the `og:type` and `og:image` properties need to be defined.
Properties can be added or custom values for defaults defined by specifying them in the page frontmatter. Example: 
```yaml
metadata:
'og:type': article 
```
Default properties can be configured, or additional properties can be added using a new 'metadata' …
=> Opengraph support

code/site/components/com_pages/template/filter/partial.php
Trim content to prevent markdown from being rendered inside `<pre><code></code></pre>`elements if the element is not defined at the first column of a document due to additional unwanted whitespace being added as a result of the regex filtering.
=> Markdown partials are not rendered correctly

code/site/components/com_pages/template/filter/asset.php
This PR adds a image:// scheme to make it easy to create image paths and make the /images folder configurable. Default is /images
Note to generatea fully qualified image url you can do baseurl://image://[path/to/image]
=> Add an image:// scheme

code/site/components/com_pages/dispatcher/router/abstract.php, code/site/components/com_pages/dispatcher/router/resolver/abstract.php, code/site/components/com_pages/model/entity/page.php, code/site/components/com_pages/page/registry.php, code/site/components/com_pages/view/collection/rss.php, code/site/components/com_pages/view/collection/tmpl/newsfeed.rss.php, code/site/components/com_pages/view/xml.php
This PR fixes issues with and improves the RSS feed support to bring it as close as possible to the RSS specification: https://validator.w3.org/feed/docs/rss2.html
The item image is now embedded using media RSS specification: http://www.rssboard.org/media-rss instead of injecting into the description.
The channel or item description is based on the page or item summary and no longer contains html entities to stay as close to the original specification as possible.
=> Improve RSS feed

code/site/components/com_pages/controller/abstract.php, code/site/components/com_pages/model/pages.php, code/site/components/com_pages/view/collection/tmpl/sitemap.xml.php
This PR removed the 'sitemap' pages collection state. Instead a page is not included in the sitemap if it has robots: noindex defined. 
If you wish to define robots in your metadata you need to define it as an array 
```yaml
metadata:
robots: [noindex, nofollow]
```
Note: as part of the this PR a metadata property now accepts array values, if an array is defined thit will be imploded using a ',' separator.
=> Refactor sitemap handling

code/site/components/com_pages/dispatcher/router/resolver/http.php
To test: route('[page]#fragment') should return  http://mysite.com/[page]#fragment.
=> Router cannot handle fragments

code/site/components/com_pages/model/pages.php, code/site/components/com_pages/page/registry.php
This PR fixes two issues:
1. The 'index' pages are not in the sitemap. To test http://joomlatools.com/extensions was not present, this should be fixed now. Do also confirm that the http://joomlatools.com is still present
2. As a result of a previous fix the index pages got included in the navigation while they should only have been included in the sitemap. To test ensure that we don't have double menu items anymore.
=> Sitemap doesn't contain all pages

code/site/components/com_pages/controller/abstract.php, code/site/components/com_pages/model/entity/page.php, code/site/components/com_pages/view/html.php
This PR adds support for setting the page direction. The direction can be defined through the page frontmatter 'direction' option.
```yaml
collection: [auto|ltr|rtl]
```
By default the direction is set to 'auto' which is supported by all html5 capable browsers. For more info see: https://www.w3.org/International/questions/qa-html-dir#dirauto
=> Add support for dir attribute

code/site/components/com_pages/page/registry.php
This PR ensures that a page folder is by default ordered alphabetically, unless there is a .order file present that specifies a custom order.
=> Improve page ordering

code/site/components/com_pages/dispatcher/http.php, code/site/components/com_pages/dispatcher/router/resolver/redirect.php
This PR allows for internal and external redirects.
- **internal redirect:** should point to an internal page path and not use a url, the redirect will use a  307 status code and is temporary
- **external redirect:** should point to an external url and not use a page path, the redirect will use a 301 status code and is permanent.
=> Internal redirect should be a 307

code/site/components/com_pages/template/default.php
This PR combines the attribute and attributes functionality into one attributes() function. The function has two signature now:
- attributes($key, $value)
- attributes($array)
Method has also been optimised to properly handle empty values.
=> Combine attribute and attributes into attributes

code/site/components/com_pages/page/registry.php
This PR changes the pages registry indexing and will index every directory regardless if the directory has a 'index.*' file or not. To prevent a folder from being indexed, add a .ignore file to the directory.
=> Do not require an index file

code/site/components/com_pages/controller/abstract.php, code/site/components/com_pages/dispatcher/behavior/decoratable.php, code/site/components/com_pages/dispatcher/router/resolver/site.php, code/site/components/com_pages/event/subscriber/htmlpurifier.php, code/site/components/com_pages/event/subscriber/pagedecorator.php, code/site/components/com_pages/page/registry.php, code/site/components/com_pages/resources/config/bootstrapper.php, code/site/components/com_pages/resources/config/options.php, code/site/components/com_pages/template/filter/asset.php, code/site/components/com_pages/template/filter/meta.php, code/site/components/com_pages/template/filter/whitespace.php, code/site/components/com_pages/template/locator/theme.php, code/site/components/com_pages/view/html.php
This PR implements theme support for pages. A default installation of pages can include a /theme folder to facilitate loading of specific assets (css, js,and images ...), and additionally it is now possible to  completely control the html output, bypassing the Joomla template system.
The /theme directory can be used to load assets. The theme:// template alias allow to easily define urls that point to the theme directory.
Pages now provides complete control over the generated html and can run outside of the context of the active Joomla template.  
To do so render a complete html document. Pages will detect the presence of a `<html>` element and if it does will output the page directly, not forwarding it to Joomla for further processing.
The `aliases` config setting allows to define the …
=> Theme support

code/site/components/com_pages/controller/abstract.php, code/site/components/com_pages/dispatcher/http.php, code/site/components/com_pages/event/subscriber/errorhandler.php, code/site/components/com_pages/page/registry.php, code/site/components/com_pages/resources/config/bootstrapper.php
This PR implements support for custom error pages.  If an error happens pages will look for a error page in the pages root folder `/joomlatools-pages/pages` The error page should return a complete html document.
Custom error pages need to be added to the root ‘/pages’, the page name should match the error code.  For example. In case of a `404 - Not Found` error pages will look for `/joomlatools-pages/pages/404.html` page.
- If  a matching error page for the error code cannot be found Pages will fallback and look for the 500.html.php
- If no error page exists Pages will let Joomla handle the error instead. 
In case you don’t want the error page to be routable, aka accessible through the browser you can set the page route to `false`
Example:
```yaml
---
route: false
title: 404 Page not …
```
=> Custom error pages

code/site/components/com_pages/template/default.php, code/site/components/com_pages/template/helper/snippet.php
This PR adds support for snippets. A snippet behaves just like a double-quoted string, without the double quotes. This means that quotes in a snippet do not need to be escaped, but the escape codes can still be used. Variables are expanded, but the same care must be taken when expressing complex variables as with strings.
Snippets are for example useful to allow html code generated by helpers to be overridable, for a template, this can provide added flexibility to helpers.
The snippet helper exposes two methods
- `snippet.define`
- `snippet.expand`
For example 
1. To define the snippet
````php
<? $snippet = '
<a class="button" href="$url" $attributes>
$icon<span>$label</span>
</a>'
?>
<? helper('snippet.define', 'button', $snippet) ?>
````
2. To expend the snippet
````php
<? …
```
=> Add snippets support

code/site/components/com_pages/page/registry.php
This PR applies a hotfix to remove filter placeholder from the content. The solution a quick fix to the problem and chosen to to filter the content, instead leave this up to the consumer of the content.
=> JSON html output is't filtered

code/site/components/com_pages/model/entity/item.php
This PR improves var_dump() page objects. If a property is an object and it implements __debugInfo() call it, if it can be casted to a string cast it, if not return the class name only.
=> Improve var_dump support for page objects

code/site/components/com_pages/model/entity/page.php
This PR adds a getParent() method to the page entity to easily retrieve the current page parent entity.
=> Add getParent() method to page entity

code/site/components/com_pages/event/subscriber/bootstrapper.php, code/site/components/com_pages/resources/config/site.php
This PR add implement autoloading support for composer vendor libraries.  
- By default the composer autoloader will be loaded from /joomlatools-pages/vendor
- A new  `composer_path`config option to allows to define a custom location for the vendor folder.
=> Allow autoloading vendor libraries

code/site/components/com_pages/data/object.php, code/site/components/com_pages/object/config/xml.php, code/site/components/com_pages/resources/config/bootstrapper.php
This PR implements improvements to the data api to better support complex xml structures. 
The xml parser has been improved to handle node attributes. If an element has attributes the attributes are parsed into an `@attributes` array and the node value is parsed into a `@value` element
Example: `['@attrributes' => [], '@value' => '']`
The `get()` method has been improved to allow to return an item by it's path. 
For example: `data('tree')->get('path/to/node);`
The `filter()` method has been improved to to accept an array as value. A new `strict` method
parameter defines if the value check should be strict or not, if strict the value needs to be identical, if not, the value needs to be present in the item.
For example: ` data('tree')->get('path/to/node')->filter('@attributes', …
=> Improve xml data support

code/site/components/com_pages/data/locator.php, code/site/components/com_pages/data/registry.php, code/site/components/com_pages/resources/config/site.php
This PR implements support for data namespaces and allow to load data from different pre-configured locations. 
Namespaces are defined through the new `data_namespaces` config option which is an associative array. Example:
````php
'data_namespaces' => [
'global' => JPATH_ROOT . '/data'
],
````
Data can be loaded from a named location by prefixing the path with the name of the location as follows: `data([namespace]://[path/to/data])`
Example: `data(global://config)`
This PR also adds support for loading external files by absolute path. Similar to loading data through http. Syntax is `file://path/to/data.json`
=> Data namespaces

code/site/components/com_pages/data/registry.php, code/site/components/com_pages/page/registry.php, code/site/components/com_pages/resources/config/site.php
This PR implements an automatic cache validation mechanism for the page and data cache. If cache validation is enabled a cache key will be calculated based on the filemtime of each file which is validated each time the cache is loaded
- The  `page_cache_time` config option has been removed and replace it with a `page_cache_validation` config option. Default is TRUE.
- The  `data_cache_time` config option has been removed and replace it with a `data_cache_validation` config option. Default is TRUE.
Page and data caching can be enabled by default and will work seamlessly. (This was already the case for the template cache).
=> Automatic page and data cache validation

code/administrator/components/com_pages/pages.xml, code/site/components/com_pages/data/object.php, code/site/components/com_pages/data/registry.php, code/site/components/com_pages/object/config/html.php, code/site/components/com_pages/object/config/xml.php, code/site/components/com_pages/page/registry.php, code/site/components/com_pages/resources/config/bootstrapper.php, code/site/components/com_pages/template/default.php
This PR adds support for html files to[ the data API](https://github.com/joomlatools/joomlatools-pages/wiki/Data). It adds two main improvements:
1. Loading data files by url
2. Loading and parsing html files
It's now possible to load any type of structured data file by file by url. For example: `data([url])`. If the file is a html or xml file it will be parsed to an array DomDocument, attributes, text and comment node are treated in a special way. (See also: https://github.com/joomlatools/joomlatools-pages/pull/248)
Following new methods have been added to the data API to make it possible to cast a data object to a specific format, and in case of html or xml manipulate it using the Dom and/or XPath expressions before serialising it to string.
This method will return a `DomDocumentXml`. …
=> Include any static html page

code/site/components/com_pages/config.php, code/site/components/com_pages/dispatcher/http.php, code/site/components/com_pages/dispatcher/router/resolver/regex.php, code/site/components/com_pages/event/subscriber/bootstrapper.php, code/site/components/com_pages/event/subscriber/dispatcher.php, code/site/components/com_pages/event/subscriber/pagedecorator.php, code/site/components/com_pages/resources/config/bootstrapper.php
This PR fixes issues with multi-site routing. 
1. This PR removes the requirement for any menu items, pages will work without a menu item, a Pages menu item can still be used to create Joomla menu's but doesn't offer any additional functionality. 
2. This PR changes how the decorator works. [Decoration](https://github.com/joomlatools/joomlatools-pages/wiki/Decoration) now always needs to be enabled by setting `decorate` to `true`
=> Issues with multi-site routing

code/site/components/com_pages/event/subscriber/bootstrapper.php, code/site/components/com_pages/event/subscriber/dispatcher.php
This PR requires: https://github.com/joomlatools/joomlatools-framework/pull/352
This PR adds support for per page Joomla template configuration. It adds a `template` config option to the process in the frontmatter.
````yaml
---
process:
template:
name: Beez3
config:
templatecolor: red
modules: ["Main Menu", 17]
---
````
- `name`: Defines the name of the template to use
- `config`: Defines an associative array of template config overrides
- `modules`: Defines a list of modules to include, either by name or by id.
By default modules are limited to the list provided. This allows to ensure no other modules then those listed can be present on the page. If the list is empty no modules will be included in the page. 
Example: `modules: ["Main Menu", 17]`
If the module name or module id is …
=> Template configuration support

code/site/components/com_pages/page/registry.php
This PR adds an 'extend' option to the collection frontmatter and allows to extend another collection. For example, in case we have following collection defined on the page /pages/blog.html.php
````yaml
---
collection:
state:
folder: blog
limit: 10
sort: date
order: desc
collection: false
page:
layout: blog/post
metadata:
'og:type': article
---
````
We can extend it as follows to only return the pages tagged with `foo` and `bar` 
````yaml
---
collection:
extend: blog
state:
limit: 4
filter: 'tags in foo and tags in bar'
---
````
=> Allow to extend a collection

code/site/components/com_pages/model/entity/page.php
This PR adds support for the Opengraph locale metadata tag. If the page language property is not empty it will be set as the og:locale metadata tag
=> Add support for og:locale metadata tag

code/site/components/com_pages/config.php, code/site/components/com_pages/event/subscriber/bootstrapper.php, code/site/components/com_pages/resources/config/site.php, code/site/components/com_pages/template/default.php
This PR refactors the config handling and adds a `config()`template function which gives easy access to both the site runtime configuration as the configuration of extensions or other objects.
````php
<?= config()->http_cache ?>
````
To access the site configuration simply call the config function with no arguments. 
````php
<?= config('ext:template.helper.foo')->bar ?>
````
To access a specific objects its configuration you can call the config method with the object identifier.
=> Add config() template function

code/site/components/com_pages/config.php
This PR enabled following config options by default:
- `page_cache: true`
- `data_cache: true`
- `template_cache: true`
=> Enable page, data and template caching by default

code/site/components/com_pages/model/collection.php, code/site/components/com_pages/model/database.php, code/site/components/com_pages/model/filesystem.php, code/site/components/com_pages/model/webservice.php
This PR moves the logic to define new states to the collection, and makes it available to database collections too. 
This allows to filter any collection, either by hardcoding a new state, or through a dynamic page route.  The state name needs to be the same as the database column name. 
For example. Let's consider following page, which is listing users and allows the result to be filtered by user group. 
````yaml
---
route: users/[digit:group_id]?
collection:
model: database?table=users
---
````
The users database table has a `group_id` column that defines the group id as an integer.  We can now list all users as `http://example.com/users` or we can list all users of a specific group as `http://example.com/users/1`
If we do not want to make the state dynamic, but instead want to only …
=> Automatically set new collection states

code/site/components/com_pages/model/behavior/filterable.php
This PR adds support for multiple filter constraints for the same attribute. For example:
Through frontmatter:
````yaml
---
collection:
model: database?table=bar
state:
filter:
foo:
- 'gt:1'
- 'lt:10'
---
````
Through url:
`http://example.com/bar?filter[id][]=gt:1&filter[id][]=lt:10`
=> Multiple filter constraints

code/site/components/com_pages/dispatcher/behavior/cacheable.php, code/site/components/com_pages/dispatcher/http.php, code/site/components/com_pages/resources/scripts/proxy.php
This PR refactors the http cache proxy to support async cache validation.  Changes:
- The proxy now accepts and  anonymous function that will call the application. 
- The proxy no longer handles cache expiration, only etag based cache validation is supported. 
The proxy will return the resource from cache immediately if it exists and validate it async in the background. This ensure that each request is equally fast.
The proxy uses [fastcgi_finish_request();](https://www.php.net/manual/en/function.fastcgi-finish-request.php) to flush all response data to the client. 
Note: [PFM](https://www.php.net/manual/en/install.fpm.php) is required
- PROXY-REFRESHED and PROXY-HIT cache status codes have been removed
=> Async Http Cache Proxy

code/site/components/com_pages/model/behavior/sortable.php
Requires: https://github.com/joomlatools/joomlatools-framework/pull/363
This PR adds support for the `shuffle` ordering to the database collection. 
Through frontmatter
````yaml
---
collection:
model: database?table=content
state:
order: shuffle
---
````
Through url
http://example.com/bar?order=shuffle
=> Add support for shuffle to database collection

code/site/components/com_pages/dispatcher/http.php
This PR adds the `X-Robots-Tag` header for `GET` or `HEAD` requests if robots metadata is specified for the page.
For more details on the robots meta tags see: https://developers.google.com/search/reference/robots_meta_tag
=> Add X-Robots-Tag header

code/site/components/com_pages/dispatcher/behavior/cacheable.php, code/site/components/com_pages/model/cache.php, code/site/components/com_pages/page/registry.php, code/site/components/com_pages/resources/config/site.php, code/site/components/com_pages/view/json.php
This PR implements a cache collection which uses the http cache as data source. It can be used to expose the cache externally, for example to build an external cache (re)generator or can be used to build a sitemap.
Example: /cache.json
````yaml
---
collection:
model: cache
state:
limit: 0
process:
cache: false
metadata:
robots: [noindex]
---
````
The cache collection exposes following data attributes:
- `id`:  The id of the cache, allows to lookup the actual file on the filesystem
-  `url`: The url that was used to generate the cache
- `date`: The data the cache was generated
-  `hash`: The hash
- `language`: The page language
- `tags`: The page tags
- `robots`: The page robots metadata
The cache collection can also be used to build a sitemap, however is this case the sitemap will be …
=> Cache collection

code/site/components/com_pages/data/object.php
This PR fixes an inconsistencies in the returned result of the `data::find()` and `data:filter()` methods.
=> Do no return an array if we only found a single scalar result

code/site/components/com_pages/page/registry.php
This PR adds a default `pages` collection. To use:
```yaml
---
collection:
extend: pages
state:
folder: blog
sort: date
order: desc
---
````
````php
<? $pages = collection('pages', ['folder' => 'blog', 'sort' => 'date', 'order' => 'desc']); ?>
````
=> Add a default pages collection

code/site/components/com_pages/controller/processor/csv.php
Encode multi-dimensional data to comma seperated string or to json and unset objects that cannot be casted to string.
=> Add support for multi-dimensional data to CSV form processor

code/site/components/com_pages/model/collection.php, code/site/components/com_pages/model/factory.php
This method will return the name of the collection used to create the model and allows to specialise the model behavior targetting a specific collection.
Example:
````php
<?php
class ExtensionModelArticles extends ComPagesModelDatabase
{
protected function _initialize(KObjectConfig $config)
{
$config->append(array(
'table'  => 'content',
));
parent::_initialize($config);
}
public function fetchData($count = false)
{
$query = parent::fetchData($count = false);
if($this->getName() == 'blog' && !$this->getObject('user')->isAuthentic())
{
$date = gmdate('Y-m-d H:i:s', strtotime('1 week ago'));
$query->where('tbl.created < :date')->bind(['date' => $date]);
}
return $query;
}
}
````
=> Add ComPagesCollection::getName() method

code/site/components/com_pages/model/webservice.php
This PR adds a new `data` config option to define the name or path fo the data element.  
````yaml
---
collection:
model: webservice
config: 
url: 'example.com?format=json&x=y'
data: ['path', 'to', 'items']
---
````
_Note:_ the data can also be written as a string: `path/to/items`
````yaml
---
collection:
model: webservice?url=example.com?format=json%26x=y&data=path%2Fto%2Fitems
---
````
_Note:_ when using the url notation the url and data value needs to be properly encoded: `& =>  %26` and `/ => %2F`
Example to get data from the K2 demo site:
````php
---
collection:
model: webservice?url=https://getk2.org/showcase?format=json&data=items
---
<ul>
<? foreach(collection() as $item): ?>
<li><?= $item->title ?></li>
<? endforeach; ?>
</ul>
````
=> Allow to configure data root path for a webservice collection

code/site/components/com_pages/dispatcher/router/resolver/pagination.php
This PR fixes the `Division by Zero error` when the `limit` is set to 0
=> Division by zero error when limit is 0 

code/site/components/com_pages/event/subscriber/pagedecorator.php
This PR changes the decorator filter to LOW priority to ensure it runs after the other template filters. By using LOW we still allow for any LOWEST priority filters to be run. 
Filtering the decorated component content can lead to unwanted side-effects when for example component specific inline `<script>`or `<style>` elements are being filtered and moved to the head.
=> Do not filter decorated component content

code/site/components/com_pages/class/locator/extension.php, code/site/components/com_pages/event/subscriber/bootstrapper.php, code/site/components/com_pages/object/locator/extension.php
This PR implements support for extension bundles and changes the extension identifier and classname scheme. Both now need to include the package. The type is now also `ext` for both.
- identifier: `ext:[package].[path].[file]`
- classname: `Ext[Package][Path][File]`
Extensions are now bundled inside their own package directory, format: `/joomlatools-pages/extensions/[package]`
=> Extension bundles

code/site/components/com_pages/controller/abstract.php, code/site/components/com_pages/dispatcher/http.php, code/site/components/com_pages/event/subscriber/errorhandler.php, code/site/components/com_pages/template/helper/behavior.php
This PR fixes #453 and also adds a catch all for all Joomla exceptions and routes them through the pages error handling.
=> Error handling not working

code/site/components/com_pages/model/behavior/filterable.php
This PR #closed #476 and fixes and issue with multiple nested filter constraints not working. See also: https://github.com/joomlatools/joomlatools-pages/pull/413
For example, get a list of all the pages that are indexable:
````yaml
---
collection:
model: pages
state:
filter:
metadata:
robots:  ['nin:noindex', 'nin:none'],
---
````
`http://example.com/bar?filter[metadata][robots][]=nin:noindex&filter[metadata][robots][]=nin:none`
````php
<? $pages = collection('pages', [
'filter' => [
'metadata' => [
'robots' => ['nin:noindex', 'nin:none'],
],
]
]); ?>
=> Handle multiple nested constraints correctly

code/administrator/components/com_pages/pages.xml, code/administrator/components/com_pages/version.php, code/site/components/com_pages/model/webservice.php
This PR closes #478 and adds a new `headers` config option to easily define custom headers. For example:
```yaml
---
collection:
model: webservice
config:
url: http://www.example.com/api/records.json
headers: 
Authorization: Bearer [key]
---
```
=> Improve webservice collection

code/site/components/com_pages/event/subscriber/staticcache.php
This PR closes #490 and improve the static caching logic. A page will not be cached statically if it must be revalidated. This allows to set a global cache time for the static cache and still define a different cache time per page.
=> Do not cache statically if must-revalidate

code/site/components/com_pages/event/subscriber/dispatcher.php, code/site/components/com_pages/event/subscriber/errorhandler.php, code/site/components/com_pages/event/subscriber/pagedecorator.php
This PR closes #498 and solves an issue with Pages trying to dispatch none-sef request. This fix checks of the request contains `option=com_[foo]` and if this is the case disabled the pages dispatcher, error handler and page decorator.
=> Do not intercept none-sef request

code/site/components/com_pages/dispatcher/behavior/cacheable.php, code/site/components/com_pages/event/subscriber/staticcache.php, code/site/components/com_pages/resources/server/apache.txt
This PR closes #500 and prevents redirects from getting cached. It also improves the staticcache handler and only caches statically if the cache returned true.
=> Do not cache redirects

code/site/components/com_pages/config.php, code/site/components/com_pages/dispatcher/behavior/redirectable.php, code/site/components/com_pages/dispatcher/http.php, code/site/components/com_pages/dispatcher/router/abstract.php, code/site/components/com_pages/dispatcher/router/redirect.php, code/site/components/com_pages/dispatcher/router/resolver/regex.php
This PR closes #502 and allows the redirect router to handle /index.php in routes if the request is rewritten if not /index.php/ will not be considered as part of the path. 
The PR also adds support for redirect cache purging. This is useful when you are changing a page to a redirect, or when you move from /index.php to / rewrites and you need the cache to be cleaned.
=> Improve redirect routing

code/site/components/com_pages/event/subscriber/bootstrapper.php
This PR closes #507 and sets the PAGES_PATH env variable based on the Joomla configuration. This prevents the need to set it manually.
=> Set PAGES_PATH based on Joomla configuration

code/site/components/com_pages/config.php, code/site/components/com_pages/data/registry.php, code/site/components/com_pages/http/cache.php, code/site/components/com_pages/model/webservice.php, code/site/components/com_pages/template/default.php
This PR closes #511 and adds support for configuring the data remote data cache through the template `data()`function.
The `data([url], [cache])`template function now accepts a second `cache` parameter that allows to define the caching behavior for remote data fetched by url. By default caching is enabled and the data will not be revalidated.
The `cache` parameter accepts following options:
- `true`: enabled the cache (default)
- `false`: disabled the cache
- '3600`: time in seconds the cache is valid
- `1day`: an English textual relative datetime format the cache is valid
Example: `<? $data = data([url], '1day'); ?>`
This PR also removed the following configuration options
- `http_resource_cache_time` 
- `http_resource_cache_force`
Both options are no longer used http caching needs to be …
=> Improve remote data caching

code/site/components/com_pages/model/collection.php
This PR closes #513 and allows to define the searchable collection properties through the collection frontmatter definition.
The data properties that can be searched on need to be defined, if no properties are defined search will not work. You can define one or multiple properties to search on. 
_Note:_ searching is done on the raw data, not on the processed entities, converting the data to entities happens after the data has been retrieved from the datastore.
To allow search on the name and email of a user define the `name` and `email` property as searcheable create a file `/joomlatools-pages/pages/users.html.php` with the following definition:
```yaml
---
collection:
model: database?table=users
config:
search: [name, email]
---
```
```php
<ul>
<? foreach(collection() as $user): ?> …
```
=> Allow to define searchable collection properties

code/site/components/com_pages/model/collection.php, code/site/components/com_pages/model/filesystem.php
This PR closes #515 and fixes an issue with a filesystem model always creating an identity key value even if the key exists in the entity.
=> Filesystem collection identity issue
